using System.Text.Json.Serialization;
using SquareConnectApi.Core.Enum;

namespace SquareConnectApi.Models.Enums;

/// <summary>
/// Indicates the source that generated the gift card
/// account number (GAN).
/// </summary>
[JsonConverter(typeof(StringEnumConverter<GiftCardGansource>))]
public sealed record GiftCardGansource : StringEnum<GiftCardGansource>
{
    private GiftCardGansource(string value) : base(value)
    {
    }

    /// <summary>
    /// The gift card account number (GAN) is generated by Square.
    /// </summary>
    public static readonly GiftCardGansource Square = new("SQUARE");

    /// <summary>
    /// The gift card account number (GAN) is imported from a non-Square system.
    /// For more information, see
    /// <see href="https://developer.squareup.com/docs/gift-cards/using-gift-cards-api#third-party-gift-cards">Third-party gift cards</see>.
    /// </summary>
    public static readonly GiftCardGansource Other = new("OTHER");

    public static GiftCardGansource FromValue(string value) => FromValueCore(value);
}
