using System.Text.Json.Serialization;
using SquareConnectApi.Core.Enum;

namespace SquareConnectApi.Models.Enums;

/// <summary>
/// Defines whether the event was generated by the Square Point of Sale.
/// </summary>
[JsonConverter(typeof(StringEnumConverter<LoyaltyEventSource>))]
public sealed record LoyaltyEventSource : StringEnum<LoyaltyEventSource>
{
    private LoyaltyEventSource(string value) : base(value)
    {
    }

    /// <summary>
    /// The event is generated by the Square Point of Sale (POS).
    /// </summary>
    public static readonly LoyaltyEventSource Square = new("SQUARE");

    /// <summary>
    /// The event is generated by something other than the Square Point of Sale that used the Loyalty API.
    /// </summary>
    public static readonly LoyaltyEventSource LoyaltyApi = new("LOYALTY_API");

    public static LoyaltyEventSource FromValue(string value) => FromValueCore(value);
}
