using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using SquareConnectApi.Core;
using SquareConnectApi.Core.ErrorResponse;
using SquareConnectApi.Core.Exceptions;
using SquareConnectApi.Core.Models;
using SquareConnectApi.Core.Request;
using SquareConnectApi.Core.Response;
using SquareConnectApi.Models;

namespace SquareConnectApi.Api;

public sealed class Merchants
{
    private readonly RawClient _rawClient;
    private readonly Server _server;
    private readonly AuthSchemes _auth;

    internal Merchants(RawClient rawClient, Server server, AuthSchemes auth)
    {
        _rawClient = rawClient;
        _server = server;
        _auth = auth;
    }

    /// <summary>
    /// ListMerchants
    /// </summary>
    /// <param name="cursor">The cursor generated by the previous response.</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="ListMerchantsResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Returns <c>Merchant</c> information for a given access token.
    /// <para>
    /// If you don't know a <c>Merchant</c> ID, you can use this endpoint to retrieve the merchant ID for an access token.
    /// You can specify your personal access token to get your own merchant information or specify an OAuth token
    /// to get the information for the  merchant that granted you access.
    /// </para>
    /// <para>
    /// If you know the merchant ID, you can also use the <see href="https://developer.squareup.com/reference/square_2021-08-18/merchants-api/retrieve-merchant">RetrieveMerchant</see>
    /// endpoint to get the merchant information.
    /// </para>
    /// </remarks>
    public Task<ListMerchantsResponse> ListMerchants(int? cursor, CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/v2/merchants"),
            [],
            [new Param("cursor", cursor)],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<ListMerchantsResponse>(),
            RawErrorResponse.Instance,
            [_auth.Oauth2],
            ct);

    /// <summary>
    /// RetrieveMerchant
    /// </summary>
    /// <param name="merchantId">The ID of the merchant to retrieve. If the string "me" is supplied as the ID, then retrieve the merchant that is currently accessible to this call.</param>
    /// <param name="ct">Cancellation token</param>
    /// <returns>A <see cref="Task{TResult}"/> of <see cref="RetrieveMerchantResponse"/> instance.</returns>
    /// <exception cref="SdkException{TResult}"> of <see cref="RawError"/> when the server returns an error response.</exception>
    /// <remarks>
    /// Retrieve a <c>Merchant</c> object for the given <c>merchant_id</c>.
    /// </remarks>
    public Task<RetrieveMerchantResponse> RetrieveMerchant(string merchantId, CancellationToken ct = default) =>
        _rawClient.Execute(_server.Default("/v2/merchants/{merchant_id}"),
            [new TemplateParam("merchant_id", merchantId)],
            [],
            [],
            HttpMethod.Get,
            EmptyBody.Instance,
            JsonResponse.Create<RetrieveMerchantResponse>(),
            RawErrorResponse.Instance,
            [_auth.Oauth2],
            ct);
}
