using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Reflects the current status of a card payment. Contains only non-confidential information.
/// </summary>
public record CardPaymentDetails
{
    /// <summary>
    /// For EMV payments, the cryptogram generated for the payment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("application_cryptogram")]
    [MaxLength(16)]
    public string? ApplicationCryptogram { get; init; }

    /// <summary>
    /// For EMV payments, the application ID identifies the EMV application used for the payment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("application_identifier")]
    [MaxLength(32)]
    public string? ApplicationIdentifier { get; init; }

    /// <summary>
    /// For EMV payments, the human-readable name of the EMV application used for the payment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("application_name")]
    [MaxLength(16)]
    public string? ApplicationName { get; init; }

    /// <summary>
    /// The status code returned by the card issuer that describes the payment's
    /// authorization status.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("auth_result_code")]
    [MaxLength(10)]
    public string? AuthResultCode { get; init; }

    /// <summary>
    /// The status code returned from the Address Verification System (AVS) check. The code can be
    /// <c>AVS_ACCEPTED</c>, <c>AVS_REJECTED</c>, or <c>AVS_NOT_CHECKED</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("avs_status")]
    [MaxLength(50)]
    public string? AvsStatus { get; init; }

    /// <summary>
    /// Represents the payment details of a card to be used for payments. These
    /// details are determined by the payment token generated by Web Payments SDK.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("card")]
    public Card? Card { get; init; }

    /// <summary>
    /// The timeline for card payments.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("card_payment_timeline")]
    public CardPaymentTimeline? CardPaymentTimeline { get; init; }

    /// <summary>
    /// The status code returned from the Card Verification Value (CVV) check. The code can be
    /// <c>CVV_ACCEPTED</c>, <c>CVV_REJECTED</c>, or <c>CVV_NOT_CHECKED</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cvv_status")]
    [MaxLength(50)]
    public string? CvvStatus { get; init; }

    /// <summary>
    /// Details about the device that took the payment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("device_details")]
    public DeviceDetails? DeviceDetails { get; init; }

    /// <summary>
    /// The method used to enter the card's details for the payment. The method can be
    /// <c>KEYED</c>, <c>SWIPED</c>, <c>EMV</c>, <c>ON_FILE</c>, or <c>CONTACTLESS</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("entry_method")]
    [MaxLength(50)]
    public string? EntryMethod { get; init; }

    /// <summary>
    /// Information about errors encountered during the request.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("errors")]
    public IReadOnlyList<Error>? Errors { get; init; }

    /// <summary>
    /// Whether the card must be physically present for the payment to
    /// be refunded.  If set to <c>true</c>, the card must be present.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("refund_requires_card_presence")]
    public bool? RefundRequiresCardPresence { get; init; }

    /// <summary>
    /// The statement description sent to the card networks.
    /// <para>
    /// Note: The actual statement description varies and is likely to be truncated and appended with
    /// additional information on a per issuer basis.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("statement_description")]
    [MaxLength(50)]
    public string? StatementDescription { get; init; }

    /// <summary>
    /// The card payment's current state. The state can be AUTHORIZED, CAPTURED, VOIDED, or
    /// FAILED.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("status")]
    [MaxLength(50)]
    public string? Status { get; init; }

    /// <summary>
    /// For EMV payments, the method used to verify the cardholder's identity. The method can be
    /// <c>PIN</c>, <c>SIGNATURE</c>, <c>PIN_AND_SIGNATURE</c>, <c>ON_DEVICE</c>, or <c>NONE</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("verification_method")]
    [MaxLength(50)]
    public string? VerificationMethod { get; init; }

    /// <summary>
    /// For EMV payments, the results of the cardholder verification. The result can be
    /// <c>SUCCESS</c>, <c>FAILURE</c>, or <c>UNKNOWN</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("verification_results")]
    [MaxLength(50)]
    public string? VerificationResults { get; init; }
}
