using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// An image file to use in Square catalogs. It can be associated with catalog
/// items, item variations, and categories.
/// </summary>
public record CatalogImage
{
    /// <summary>
    /// A caption that describes what is shown in the image. Displayed in the
    /// Square Online Store. This is a searchable attribute for use in applicable query filters
    /// using the <see href="https://developer.squareup.com/reference/square_2021-08-18/catalog-api/search-catalog-objects">SearchCatalogObjects</see>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("caption")]
    public string? Caption { get; init; }

    /// <summary>
    /// The internal name to identify this image in calls to the Square API.
    /// This is a searchable attribute for use in applicable query filters
    /// using the <see href="https://developer.squareup.com/reference/square_2021-08-18/catalog-api/search-catalog-objects">SearchCatalogObjects</see>.
    /// It is not unique and should not be shown in a buyer facing context.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// The URL of this image, generated by Square after an image is uploaded
    /// using the <see href="https://developer.squareup.com/reference/square_2021-08-18/catalog-api/create-catalog-image">CreateCatalogImage</see> endpoint.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("url")]
    public string? Url { get; init; }
}
