using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Defines how discounts are automatically applied to a set of items that match the pricing rule
/// during the active time period.
/// </summary>
public record CatalogPricingRule
{
    /// <summary>
    /// __Deprecated__: Please use the <c>exclude_products_id</c> field to apply
    /// an exclude set instead. Exclude sets allow better control over quantity
    /// ranges and offer more flexibility for which matched items receive a discount.
    /// <para>
    /// <c>CatalogProductSet</c> to apply the pricing to.
    /// An apply rule matches within the subset of the cart that fits the match rules (the match set).
    /// An apply rule can only match once in the match set.
    /// If not supplied, the pricing will be applied to all products in the match set.
    /// Other products retain their base price, or a price generated by other rules.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("apply_products_id")]
    public string? ApplyProductsId { get; init; }

    /// <summary>
    /// A list of IDs of customer groups, the members of which are eligible for discounts specified in this pricing rule.
    /// Notice that a group ID is generated by the Customers API.
    /// If this field is not set, the specified discount applies to matched products sold to anyone whether the buyer
    /// has a customer profile created or not. If this <c>customer_group_ids_any</c> field is set, the specified discount
    /// applies only to matched products sold to customers belonging to the specified customer groups.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("customer_group_ids_any")]
    public IReadOnlyList<string>? CustomerGroupIdsAny { get; init; }

    /// <summary>
    /// Unique ID for the <c>CatalogDiscount</c> to take off
    /// the price of all matched items.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("discount_id")]
    public string? DiscountId { get; init; }

    /// <summary>
    /// <c>CatalogProductSet</c> to exclude from the pricing rule.
    /// An exclude rule matches within the subset of the cart that fits the match rules (the match set).
    /// An exclude rule can only match once in the match set.
    /// If not supplied, the pricing will be applied to all products in the match set.
    /// Other products retain their base price, or a price generated by other rules.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("exclude_products_id")]
    public string? ExcludeProductsId { get; init; }

    /// <summary>
    /// If an <c>exclude_products_id</c> was given, controls which subset of matched
    /// products is excluded from any discounts.
    /// <para>
    /// Default value: <c>LEAST_EXPENSIVE</c>
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("exclude_strategy")]
    public string? ExcludeStrategy { get; init; }

    /// <summary>
    /// Unique ID for the <c>CatalogProductSet</c> that will be matched by this rule. A match rule
    /// matches within the entire cart, and can match multiple times. This field will always be set.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("match_products_id")]
    public string? MatchProductsId { get; init; }

    /// <summary>
    /// User-defined name for the pricing rule. For example, "Buy one get one
    /// free" or "10% off".
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>
    /// A list of unique IDs for the catalog time periods when
    /// this pricing rule is in effect. If left unset, the pricing rule is always
    /// in effect.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("time_period_ids")]
    public IReadOnlyList<string>? TimePeriodIds { get; init; }

    /// <summary>
    /// Represents the date the Pricing Rule is valid from. Represented in RFC 3339 full-date format (YYYY-MM-DD).
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("valid_from_date")]
    public string? ValidFromDate { get; init; }

    /// <summary>
    /// Represents the local time the pricing rule should be valid from. Represented in RFC 3339 partial-time format
    /// (HH:MM:SS). Partial seconds will be truncated.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("valid_from_local_time")]
    public string? ValidFromLocalTime { get; init; }

    /// <summary>
    /// Represents the date the Pricing Rule is valid until. Represented in RFC 3339 full-date format (YYYY-MM-DD).
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("valid_until_date")]
    public string? ValidUntilDate { get; init; }

    /// <summary>
    /// Represents the local time the pricing rule should be valid until. Represented in RFC 3339 partial-time format
    /// (HH:MM:SS). Partial seconds will be truncated.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("valid_until_local_time")]
    public string? ValidUntilLocalTime { get; init; }
}
