using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Square Checkout lets merchants accept online payments for supported
/// payment types using a checkout workflow hosted on squareup.com.
/// </summary>
public record Checkout
{
    /// <summary>
    /// Additional recipients (other than the merchant) receiving a portion of this checkout.
    /// For example, fees assessed on the purchase by a third party integration.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("additional_recipients")]
    public IReadOnlyList<AdditionalRecipient>? AdditionalRecipients { get; init; }

    /// <summary>
    /// If <c>true</c>, Square Checkout will collect shipping information on your
    /// behalf and store that information with the transaction information in your
    /// Square Dashboard.
    /// <para>
    /// Default: <c>false</c>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("ask_for_shipping_address")]
    public bool? AskForShippingAddress { get; init; }

    /// <summary>
    /// The URL that the buyer's browser should be redirected to after the
    /// checkout is completed.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("checkout_page_url")]
    public string? CheckoutPageUrl { get; init; }

    /// <summary>
    /// The time when the checkout was created, in RFC 3339 format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; init; }

    /// <summary>
    /// ID generated by Square Checkout when a new checkout is requested.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The email address to display on the Square Checkout confirmation page
    /// and confirmation email that the buyer can use to contact the merchant.
    /// <para>
    /// If this value is not set, the confirmation page and email will display the
    /// primary email address associated with the merchant's Square account.
    /// </para>
    /// <para>
    /// Default: none; only exists if explicitly set.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("merchant_support_email")]
    public string? MerchantSupportEmail { get; init; }

    /// <summary>
    /// Contains all information related to a single order to process with Square,
    /// including line items that specify the products to purchase. <c>Order</c> objects also
    /// include information about any associated tenders, refunds, and returns.
    /// <para>
    /// All Connect V2 Transactions have all been converted to Orders including all associated
    /// itemization data.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("order")]
    public Order? Order { get; init; }

    /// <summary>
    /// If provided, the buyer's email is pre-populated on the checkout page
    /// as an editable text field.
    /// <para>
    /// Default: none; only exists if explicitly set.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("pre_populate_buyer_email")]
    public string? PrePopulateBuyerEmail { get; init; }

    /// <summary>
    /// Represents a postal address in a country. The address format is based
    /// on an <see href="https://github.com/google/libaddressinput">open-source library from Google</see>. For more information,
    /// see <see href="https://github.com/google/libaddressinput/wiki/AddressValidationMetadata">AddressValidationMetadata</see>.
    /// This format has dedicated fields for four address components: postal code,
    /// locality (city), administrative district (state, prefecture, or province), and
    /// sublocality (town or village). These components have dedicated fields in the
    /// <c>Address</c> object because software sometimes behaves differently based on them.
    /// For example, sales tax software may charge different amounts of sales tax
    /// based on the postal code, and some software is only available in
    /// certain states due to compliance reasons.
    /// <para>
    /// For the remaining address components, the <c>Address</c> type provides the
    /// <c>address_line_1</c> and <c>address_line_2</c> fields for free-form data entry.
    /// These fields are free-form because the remaining address components have
    /// too many variations around the world and typical software does not parse
    /// these components. These fields enable users to enter anything they want.
    /// </para>
    /// <para>
    /// Note that, in the current implementation, all other <c>Address</c> type fields are blank.
    /// These include <c>address_line_3</c>, <c>sublocality_2</c>, <c>sublocality_3</c>,
    /// <c>administrative_district_level_2</c>, <c>administrative_district_level_3</c>,
    /// <c>first_name</c>, <c>last_name</c>, and <c>organization</c>.
    /// </para>
    /// <para>
    /// When it comes to localization, the seller's language preferences
    /// (see <see href="https://developer.squareup.com/docs/locations-api#location-specific-and-seller-level-language-preferences">Language preferences</see>)
    /// are ignored for addresses. Even though Square products (such as Square Point of Sale
    /// and the Seller Dashboard) mostly use a seller's language preference in
    /// communication, when it comes to addresses, they will use English for a US address,
    /// Japanese for an address in Japan, and so on.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("pre_populate_shipping_address")]
    public Address? PrePopulateShippingAddress { get; init; }

    /// <summary>
    /// The URL to redirect to after checkout is completed with <c>checkoutId</c>,
    /// Square's <c>orderId</c>, <c>transactionId</c>, and <c>referenceId</c> appended as URL
    /// parameters. For example, if the provided redirect_url is
    /// <c>http://www.example.com/order-complete</c>, a successful transaction redirects
    /// the customer to:
    /// <para>
    /// &lt;pre&gt;&lt;code&gt;http://www.example.com/order-complete?checkoutId=xxxxxx&amp;amp;orderId=xxxxxx&amp;amp;referenceId=xxxxxx&amp;amp;transactionId=xxxxxx&lt;/code&gt;&lt;/pre&gt;
    /// </para>
    /// <para>
    /// If you do not provide a redirect URL, Square Checkout will display an order
    /// confirmation page on your behalf; however Square strongly recommends that
    /// you provide a redirect URL so you can verify the transaction results and
    /// finalize the order through your existing/normal confirmation workflow.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("redirect_url")]
    public string? RedirectUrl { get; init; }
}
