using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Defines the fields that are included in the response body of
/// a request to the <c>CreateCustomerCard</c> endpoint.
/// <para>
/// Either <c>errors</c> or <c>card</c> is present in a given response (never both).
/// </para>
/// </summary>
public record CreateCustomerCardResponse
{
    /// <summary>
    /// Represents the payment details of a card to be used for payments. These
    /// details are determined by the payment token generated by Web Payments SDK.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("card")]
    public Card? Card { get; init; }

    /// <summary>
    /// Any errors that occurred during the request.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("errors")]
    public IReadOnlyList<Error>? Errors { get; init; }
}
