using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Defines the fields that are included in the request body of a request
/// to the <c>CreateCustomerCard</c> endpoint.
/// </summary>
public record CreateCustomerCardRequest
{
    /// <summary>
    /// Represents a postal address in a country. The address format is based
    /// on an <see href="https://github.com/google/libaddressinput">open-source library from Google</see>. For more information,
    /// see <see href="https://github.com/google/libaddressinput/wiki/AddressValidationMetadata">AddressValidationMetadata</see>.
    /// This format has dedicated fields for four address components: postal code,
    /// locality (city), administrative district (state, prefecture, or province), and
    /// sublocality (town or village). These components have dedicated fields in the
    /// <c>Address</c> object because software sometimes behaves differently based on them.
    /// For example, sales tax software may charge different amounts of sales tax
    /// based on the postal code, and some software is only available in
    /// certain states due to compliance reasons.
    /// <para>
    /// For the remaining address components, the <c>Address</c> type provides the
    /// <c>address_line_1</c> and <c>address_line_2</c> fields for free-form data entry.
    /// These fields are free-form because the remaining address components have
    /// too many variations around the world and typical software does not parse
    /// these components. These fields enable users to enter anything they want.
    /// </para>
    /// <para>
    /// Note that, in the current implementation, all other <c>Address</c> type fields are blank.
    /// These include <c>address_line_3</c>, <c>sublocality_2</c>, <c>sublocality_3</c>,
    /// <c>administrative_district_level_2</c>, <c>administrative_district_level_3</c>,
    /// <c>first_name</c>, <c>last_name</c>, and <c>organization</c>.
    /// </para>
    /// <para>
    /// When it comes to localization, the seller's language preferences
    /// (see <see href="https://developer.squareup.com/docs/locations-api#location-specific-and-seller-level-language-preferences">Language preferences</see>)
    /// are ignored for addresses. Even though Square products (such as Square Point of Sale
    /// and the Seller Dashboard) mostly use a seller's language preference in
    /// communication, when it comes to addresses, they will use English for a US address,
    /// Japanese for an address in Japan, and so on.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("billing_address")]
    public Address? BillingAddress { get; init; }

    /// <summary>
    /// A card nonce representing the credit card to link to the customer.
    /// <para>
    /// Card nonces are generated by the Square payment form when customers enter
    /// their card information. For more information, see
    /// <see href="https://developer.squareup.com/docs/web-payments/take-card-payment">Walkthrough: Integrate Square Payments in a Website</see>.
    /// </para>
    /// <para>
    /// __NOTE:__ Card nonces generated by digital wallets (such as Apple Pay)
    /// cannot be used to create a customer card.
    /// </para>
    /// </summary>
    [JsonPropertyName("card_nonce")]
    public required string CardNonce { get; init; }

    /// <summary>
    /// The full name printed on the credit card.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cardholder_name")]
    public string? CardholderName { get; init; }

    /// <summary>
    /// An identifying token generated by <see href="https://developer.squareup.com/reference/sdks/web/payments/objects/Payments#Payments.verifyBuyer">Payments.verifyBuyer()</see>.
    /// Verification tokens encapsulate customer device information and 3-D Secure
    /// challenge results to indicate that Square has verified the buyer identity.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("verification_token")]
    public string? VerificationToken { get; init; }
}
