using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Creates a card from the source (nonce, payment id, etc). Accessible via
/// HTTP requests at POST https://connect.squareup.com/v2/cards
/// </summary>
public record CreateCardRequest
{
    /// <summary>
    /// Represents the payment details of a card to be used for payments. These
    /// details are determined by the payment token generated by Web Payments SDK.
    /// </summary>
    [JsonPropertyName("card")]
    public required Card Card { get; init; }

    /// <summary>
    /// A unique string that identifies this CreateCard request. Keys can be
    /// any valid string and must be unique for every request.
    /// <para>
    /// Max: 45 characters
    /// </para>
    /// <para>
    /// See <see href="https://developer.squareup.com/docs/basics/api101/idempotency">Idempotency keys</see> for more information.
    /// </para>
    /// </summary>
    [JsonPropertyName("idempotency_key")]
    [MinLength(1)]
    public required string IdempotencyKey { get; init; }

    /// <summary>
    /// The ID of the source which represents the card information to be stored. This can be a card nonce or a payment id.
    /// </summary>
    [JsonPropertyName("source_id")]
    [StringLength(16384, MinimumLength = 1)]
    public required string SourceId { get; init; }

    /// <summary>
    /// An identifying token generated by <see href="https://developer.squareup.com/reference/sdks/web/payments/objects/Payments#Payments.verifyBuyer">Payments.verifyBuyer()</see>.
    /// Verification tokens encapsulate customer device information and 3-D Secure
    /// challenge results to indicate that Square has verified the buyer identity.
    /// <para>
    /// See the <see href="https://developer.squareup.com/docs/sca-overview">SCA Overview</see>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("verification_token")]
    public string? VerificationToken { get; init; }
}
