using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Represents a dispute a cardholder initiated with their bank.
/// </summary>
public record Dispute
{
    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("amount_money")]
    public Money? AmountMoney { get; init; }

    /// <summary>
    /// The ID of the dispute in the card brand system, generated by the card brand.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("brand_dispute_id")]
    [StringLength(40, MinimumLength = 1)]
    public string? BrandDisputeId { get; init; }

    /// <summary>
    /// The card brand used in the disputed payment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("card_brand")]
    public string? CardBrand { get; init; }

    /// <summary>
    /// The timestamp when the dispute was created, in RFC 3339 format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("created_at")]
    [StringLength(40, MinimumLength = 1)]
    public string? CreatedAt { get; init; }

    /// <summary>
    /// The unique ID for this <c>Dispute</c>, generated by Square.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dispute_id")]
    [StringLength(40, MinimumLength = 1)]
    public string? DisputeId { get; init; }

    /// <summary>
    /// The payment the cardholder disputed.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("disputed_payment")]
    public DisputedPayment? DisputedPayment { get; init; }

    /// <summary>
    /// The time when the next action is due, in RFC 3339 format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("due_at")]
    [StringLength(40, MinimumLength = 1)]
    public string? DueAt { get; init; }

    /// <summary>
    /// The IDs of the evidence associated with the dispute.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("evidence_ids")]
    public IReadOnlyList<string>? EvidenceIds { get; init; }

    /// <summary>
    /// The unique ID for this <c>Dispute</c>, generated by Square.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    [StringLength(40, MinimumLength = 1)]
    public string? Id { get; init; }

    /// <summary>
    /// The ID of the location where the dispute originated.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("location_id")]
    [StringLength(40, MinimumLength = 1)]
    public string? LocationId { get; init; }

    /// <summary>
    /// The dispute reason why the cardholder initiated the dispute with their bank.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }

    /// <summary>
    /// The timestamp when the dispute was reported, in RFC 3339 format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("reported_at")]
    [StringLength(40, MinimumLength = 1)]
    public string? ReportedAt { get; init; }

    /// <summary>
    /// The timestamp when the dispute was reported, in RFC 3339 format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("reported_date")]
    [StringLength(40, MinimumLength = 1)]
    public string? ReportedDate { get; init; }

    /// <summary>
    /// The current state of this dispute.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("state")]
    public string? State { get; init; }

    /// <summary>
    /// The timestamp when the dispute was last updated, in RFC 3339 format.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("updated_at")]
    [StringLength(40, MinimumLength = 1)]
    public string? UpdatedAt { get; init; }

    /// <summary>
    /// The current version of the <c>Dispute</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("version")]
    public int? Version { get; init; }
}
