using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

public record InventoryAdjustmentGroup
{
    /// <summary>
    /// Representative <c>from_state</c> for adjustments within the group. For example, for a group adjustment from <c>IN_STOCK</c> to <c>SOLD</c>,
    /// there can be two component adjustments in the group: one from <c>IN_STOCK</c>to <c>COMPOSED</c> and the other one from <c>COMPOSED</c> to <c>SOLD</c>.
    /// Here, the representative <c>from_state</c> for the <c>InventoryAdjustmentGroup</c> is <c>IN_STOCK</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("from_state")]
    public string? FromState { get; init; }

    /// <summary>
    /// A unique ID generated by Square for the
    /// <c>InventoryAdjustmentGroup</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    [MaxLength(100)]
    public string? Id { get; init; }

    /// <summary>
    /// The inventory adjustment of the composed variation.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("root_adjustment_id")]
    [MaxLength(100)]
    public string? RootAdjustmentId { get; init; }

    /// <summary>
    /// Representative <c>to_state</c> for adjustments within group. For example, for a group adjustment from <c>IN_STOCK</c> to <c>SOLD</c>,
    /// the two component adjustments in the group can be from <c>IN_STOCK</c> to <c>COMPOSED</c> and from <c>COMPOSED</c> to <c>SOLD</c>.
    /// Here, the representative <c>to_state</c> of the <c>InventoryAdjustmentGroup</c> is <c>SOLD</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("to_state")]
    public string? ToState { get; init; }
}
