using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Request object for the <see href="https://developer.squareup.com/reference/square_2021-08-18/merchants-api/list-merchants">ListMerchant</see> endpoint.
/// </summary>
public record ListMerchantsRequest
{
    /// <summary>
    /// The cursor generated by the previous response.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cursor")]
    public int? Cursor { get; init; }
}
