using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Provides information about a loyalty event.
/// For more information, see <see href="https://developer.squareup.com/docs/loyalty-api/overview/#loyalty-events">Loyalty events</see>.
/// </summary>
public record LoyaltyEvent
{
    /// <summary>
    /// Provides metadata when the event <c>type</c> is <c>ACCUMULATE_POINTS</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("accumulate_points")]
    public LoyaltyEventAccumulatePoints? AccumulatePoints { get; init; }

    /// <summary>
    /// Provides metadata when the event <c>type</c> is <c>ADJUST_POINTS</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("adjust_points")]
    public LoyaltyEventAdjustPoints? AdjustPoints { get; init; }

    /// <summary>
    /// Provides metadata when the event <c>type</c> is <c>CREATE_REWARD</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("create_reward")]
    public LoyaltyEventCreateReward? CreateReward { get; init; }

    /// <summary>
    /// The timestamp when the event was created, in RFC 3339 format.
    /// </summary>
    [JsonPropertyName("created_at")]
    [MinLength(1)]
    public required string CreatedAt { get; init; }

    /// <summary>
    /// Provides metadata when the event <c>type</c> is <c>DELETE_REWARD</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("delete_reward")]
    public LoyaltyEventDeleteReward? DeleteReward { get; init; }

    /// <summary>
    /// Provides metadata when the event <c>type</c> is <c>EXPIRE_POINTS</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("expire_points")]
    public LoyaltyEventExpirePoints? ExpirePoints { get; init; }

    /// <summary>
    /// The Square-assigned ID of the loyalty event.
    /// </summary>
    [JsonPropertyName("id")]
    [MinLength(1)]
    public required string Id { get; init; }

    /// <summary>
    /// The ID of the <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/Location">location</see> where the event occurred.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("location_id")]
    public string? LocationId { get; init; }

    /// <summary>
    /// The ID of the <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/LoyaltyAccount">loyalty account</see> in which the event occurred.
    /// </summary>
    [JsonPropertyName("loyalty_account_id")]
    [StringLength(36, MinimumLength = 1)]
    public required string LoyaltyAccountId { get; init; }

    /// <summary>
    /// Provides metadata when the event <c>type</c> is <c>OTHER</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("other_event")]
    public LoyaltyEventOther? OtherEvent { get; init; }

    /// <summary>
    /// Provides metadata when the event <c>type</c> is <c>REDEEM_REWARD</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("redeem_reward")]
    public LoyaltyEventRedeemReward? RedeemReward { get; init; }

    /// <summary>
    /// Defines whether the event was generated by the Square Point of Sale.
    /// </summary>
    [JsonPropertyName("source")]
    public required string Source { get; init; }

    /// <summary>
    /// The type of the loyalty event.
    /// </summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }
}
