using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Contains all information related to a single order to process with Square,
/// including line items that specify the products to purchase. <c>Order</c> objects also
/// include information about any associated tenders, refunds, and returns.
/// <para>
/// All Connect V2 Transactions have all been converted to Orders including all associated
/// itemization data.
/// </para>
/// </summary>
public record Order
{
    /// <summary>
    /// The timestamp for when the order reached a terminal <see href="https://developer.squareup.com/reference/square_2021-08-18/enums/OrderState">state</see>, in RFC 3339 format (for example "2016-09-04T23:59:33.123Z").
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("closed_at")]
    public string? ClosedAt { get; init; }

    /// <summary>
    /// The timestamp for when the order was created, in RFC 3339 format (for example, "2016-09-04T23:59:33.123Z").
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; init; }

    /// <summary>
    /// The ID of the <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/Customer">customer</see> associated with the order.
    /// <para>
    /// __IMPORTANT:__ You should specify a <c>customer_id</c> if you want the corresponding payment transactions
    /// to be explicitly linked to the customer in the Seller Dashboard. If this field is omitted, the
    /// <c>customer_id</c> assigned to any underlying <c>Payment</c> objects is ignored and might result in the
    /// creation of new <see href="https://developer.squareup.com/docs/customers-api/what-it-does#instant-profiles">instant profiles</see>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("customer_id")]
    [MaxLength(191)]
    public string? CustomerId { get; init; }

    /// <summary>
    /// The list of all discounts associated with the order.
    /// <para>
    /// Discounts can be scoped to either <c>ORDER</c> or <c>LINE_ITEM</c>. For discounts scoped to <c>LINE_ITEM</c>,
    /// an <c>OrderLineItemAppliedDiscount</c> must be added to each line item that the discount applies to.
    /// For discounts with <c>ORDER</c> scope, the server generates an <c>OrderLineItemAppliedDiscount</c>
    /// for every line item.
    /// </para>
    /// <para>
    /// __IMPORTANT__: If <c>LINE_ITEM</c> scope is set on any discounts in this field, using the deprecated
    /// <c>line_items.discounts</c> field results in an error. Use <c>line_items.applied_discounts</c>
    /// instead.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("discounts")]
    public IReadOnlyList<OrderLineItemDiscount>? Discounts { get; init; }

    /// <summary>
    /// Details about order fulfillment.
    /// <para>
    /// Orders can only be created with at most one fulfillment. However, orders returned
    /// by the API might contain multiple fulfillments.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("fulfillments")]
    public IReadOnlyList<OrderFulfillment>? Fulfillments { get; init; }

    /// <summary>
    /// The order's unique ID.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// The line items included in the order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("line_items")]
    public IReadOnlyList<OrderLineItem>? LineItems { get; init; }

    /// <summary>
    /// The ID of the seller location that this order is associated with.
    /// </summary>
    [JsonPropertyName("location_id")]
    [MinLength(1)]
    public required string LocationId { get; init; }

    /// <summary>
    /// Application-defined data attached to this order. Metadata fields are intended
    /// to store descriptive references or associations with an entity in another system or store brief
    /// information about the object. Square does not process this field; it only stores and returns it
    /// in relevant API calls. Do not use metadata to store any sensitive information (such as personally
    /// identifiable information or card details).
    /// <para>
    /// Keys written by applications must be 60 characters or less and must be in the character set
    /// <c>[a-zA-Z0-9_-]</c>. Entries can also include metadata generated by Square. These keys are prefixed
    /// with a namespace, separated from the key with a ':' character.
    /// </para>
    /// <para>
    /// Values have a maximum length of 255 characters.
    /// </para>
    /// <para>
    /// An application can have up to 10 entries per metadata field.
    /// </para>
    /// <para>
    /// Entries written by applications are private and can only be read or modified by the same
    /// application.
    /// </para>
    /// <para>
    /// For more information, see  <see href="https://developer.squareup.com/docs/build-basics/metadata">Metadata</see>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, string>? Metadata { get; init; }

    /// <summary>
    /// A collection of various money amounts.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("net_amounts")]
    public OrderMoneyAmounts? NetAmounts { get; init; }

    /// <summary>
    /// Pricing options for an order. The options affect how the order's price is calculated.
    /// They can be used, for example, to apply automatic price adjustments that are based on preconfigured
    /// <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogPricingRule">pricing rules</see>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("pricing_options")]
    public OrderPricingOptions? PricingOptions { get; init; }

    /// <summary>
    /// A client-specified ID to associate an entity in another system
    /// with this order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("reference_id")]
    [MaxLength(40)]
    public string? ReferenceId { get; init; }

    /// <summary>
    /// The refunds that are part of this order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("refunds")]
    public IReadOnlyList<Refund>? Refunds { get; init; }

    /// <summary>
    /// A collection of various money amounts.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("return_amounts")]
    public OrderMoneyAmounts? ReturnAmounts { get; init; }

    /// <summary>
    /// A collection of items from sale orders being returned in this one. Normally part of an
    /// itemized return or exchange. There is exactly one <c>Return</c> object per sale <c>Order</c> being
    /// referenced.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("returns")]
    public IReadOnlyList<OrderReturn>? Returns { get; init; }

    /// <summary>
    /// A set-like list of Rewards that have been added to the Order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("rewards")]
    public IReadOnlyList<OrderReward>? Rewards { get; init; }

    /// <summary>
    /// A rounding adjustment of the money being returned. Commonly used to apply cash rounding
    /// when the minimum unit of the account is smaller than the lowest physical denomination of the currency.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("rounding_adjustment")]
    public OrderRoundingAdjustment? RoundingAdjustment { get; init; }

    /// <summary>
    /// A list of service charges applied to the order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("service_charges")]
    public IReadOnlyList<OrderServiceCharge>? ServiceCharges { get; init; }

    /// <summary>
    /// Represents the origination details of an order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("source")]
    public OrderSource? Source { get; init; }

    /// <summary>
    /// The current state of the order: <c>OPEN</c>, <c>COMPLETED</c>, or <c>CANCELED</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("state")]
    public string? State { get; init; }

    /// <summary>
    /// The list of all taxes associated with the order.
    /// <para>
    /// Taxes can be scoped to either <c>ORDER</c> or <c>LINE_ITEM</c>. For taxes with <c>LINE_ITEM</c> scope, an
    /// <c>OrderLineItemAppliedTax</c> must be added to each line item that the tax applies to. For taxes
    /// with <c>ORDER</c> scope, the server generates an <c>OrderLineItemAppliedTax</c> for every line item.
    /// </para>
    /// <para>
    /// On reads, each tax in the list includes the total amount of that tax applied to the order.
    /// </para>
    /// <para>
    /// __IMPORTANT__: If <c>LINE_ITEM</c> scope is set on any taxes in this field, using the deprecated
    /// <c>line_items.taxes</c> field results in an error. Use <c>line_items.applied_taxes</c>
    /// instead.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("taxes")]
    public IReadOnlyList<OrderLineItemTax>? Taxes { get; init; }

    /// <summary>
    /// The tenders that were used to pay for the order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("tenders")]
    public IReadOnlyList<Tender>? Tenders { get; init; }

    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("total_discount_money")]
    public Money? TotalDiscountMoney { get; init; }

    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("total_money")]
    public Money? TotalMoney { get; init; }

    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("total_service_charge_money")]
    public Money? TotalServiceChargeMoney { get; init; }

    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("total_tax_money")]
    public Money? TotalTaxMoney { get; init; }

    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("total_tip_money")]
    public Money? TotalTipMoney { get; init; }

    /// <summary>
    /// The timestamp for when the order was last updated, in RFC 3339 format (for example, "2016-09-04T23:59:33.123Z").
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; init; }

    /// <summary>
    /// The version number, which is incremented each time an update is committed to the order.
    /// Orders not created through the API do not include a version number and
    /// therefore cannot be updated.
    /// <para>
    /// <see href="https://developer.squareup.com/docs/orders-api/manage-orders#update-orders">Read more about working with versions</see>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("version")]
    public int? Version { get; init; }
}
