using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Represents a tax that applies to one or more line item in the order.
/// <para>
/// Fixed-amount, order-scoped taxes are distributed across all non-zero line item totals.
/// The amount distributed to each line item is relative to the amount the item
/// contributes to the order subtotal.
/// </para>
/// </summary>
public record OrderLineItemTax
{
    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("applied_money")]
    public Money? AppliedMoney { get; init; }

    /// <summary>
    /// Determines whether the tax was automatically applied to the order based on
    /// the catalog configuration. For an example, see
    /// <see href="https://developer.squareup.com/docs/orders-api/apply-taxes-and-discounts/auto-apply-taxes">Automatically Apply Taxes to an Order</see>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("auto_applied")]
    public bool? AutoApplied { get; init; }

    /// <summary>
    /// The catalog object ID referencing <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogTax">CatalogTax</see>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("catalog_object_id")]
    [MaxLength(192)]
    public string? CatalogObjectId { get; init; }

    /// <summary>
    /// The version of the catalog object that this tax references.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("catalog_version")]
    public long? CatalogVersion { get; init; }

    /// <summary>
    /// Application-defined data attached to this tax. Metadata fields are intended
    /// to store descriptive references or associations with an entity in another system or store brief
    /// information about the object. Square does not process this field; it only stores and returns it
    /// in relevant API calls. Do not use metadata to store any sensitive information (such as personally
    /// identifiable information or card details).
    /// <para>
    /// Keys written by applications must be 60 characters or less and must be in the character set
    /// <c>[a-zA-Z0-9_-]</c>. Entries can also include metadata generated by Square. These keys are prefixed
    /// with a namespace, separated from the key with a ':' character.
    /// </para>
    /// <para>
    /// Values have a maximum length of 255 characters.
    /// </para>
    /// <para>
    /// An application can have up to 10 entries per metadata field.
    /// </para>
    /// <para>
    /// Entries written by applications are private and can only be read or modified by the same
    /// application.
    /// </para>
    /// <para>
    /// For more information, see <see href="https://developer.squareup.com/docs/build-basics/metadata">Metadata</see>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, string>? Metadata { get; init; }

    /// <summary>
    /// The tax's name.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    [MaxLength(255)]
    public string? Name { get; init; }

    /// <summary>
    /// The percentage of the tax, as a string representation of a decimal
    /// number. For example, a value of <c>"7.25"</c> corresponds to a percentage of
    /// 7.25%.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("percentage")]
    [MaxLength(10)]
    public string? Percentage { get; init; }

    /// <summary>
    /// Indicates the level at which the tax applies. For <c>ORDER</c> scoped taxes,
    /// Square generates references in <c>applied_taxes</c> on all order line items that do
    /// not have them. For <c>LINE_ITEM</c> scoped taxes, the tax only applies to line items
    /// with references in their <c>applied_taxes</c> field.
    /// <para>
    /// This field is immutable. To change the scope, you must delete the tax and
    /// re-add it as a new tax.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("scope")]
    public string? Scope { get; init; }

    /// <summary>
    /// Indicates the calculation method used to apply the tax.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// A unique ID that identifies the tax only within this order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("uid")]
    [MaxLength(60)]
    public string? Uid { get; init; }
}
