using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Represents a discount that applies to one or more line items in an
/// order.
/// <para>
/// Fixed-amount, order-scoped discounts are distributed across all non-zero line item totals.
/// The amount distributed to each line item is relative to the
/// amount contributed by the item to the order subtotal.
/// </para>
/// </summary>
public record OrderLineItemDiscount
{
    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("amount_money")]
    public Money? AmountMoney { get; init; }

    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("applied_money")]
    public Money? AppliedMoney { get; init; }

    /// <summary>
    /// The catalog object ID referencing <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogDiscount">CatalogDiscount</see>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("catalog_object_id")]
    [MaxLength(192)]
    public string? CatalogObjectId { get; init; }

    /// <summary>
    /// The version of the catalog object that this discount references.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("catalog_version")]
    public long? CatalogVersion { get; init; }

    /// <summary>
    /// Application-defined data attached to this discount. Metadata fields are intended
    /// to store descriptive references or associations with an entity in another system or store brief
    /// information about the object. Square does not process this field; it only stores and returns it
    /// in relevant API calls. Do not use metadata to store any sensitive information (such as personally
    /// identifiable information or card details).
    /// <para>
    /// Keys written by applications must be 60 characters or less and must be in the character set
    /// <c>[a-zA-Z0-9_-]</c>. Entries can also include metadata generated by Square. These keys are prefixed
    /// with a namespace, separated from the key with a ':' character.
    /// </para>
    /// <para>
    /// Values have a maximum length of 255 characters.
    /// </para>
    /// <para>
    /// An application can have up to 10 entries per metadata field.
    /// </para>
    /// <para>
    /// Entries written by applications are private and can only be read or modified by the same
    /// application.
    /// </para>
    /// <para>
    /// For more information, see <see href="https://developer.squareup.com/docs/build-basics/metadata">Metadata</see>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("metadata")]
    public IReadOnlyDictionary<string, string>? Metadata { get; init; }

    /// <summary>
    /// The discount's name.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("name")]
    [MaxLength(255)]
    public string? Name { get; init; }

    /// <summary>
    /// The percentage of the discount, as a string representation of a decimal number.
    /// A value of <c>7.25</c> corresponds to a percentage of 7.25%.
    /// <para>
    /// <c>percentage</c> is not set for amount-based discounts.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("percentage")]
    [MaxLength(10)]
    public string? Percentage { get; init; }

    /// <summary>
    /// The object ID of a <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogPricingRule">pricing rule</see> to be applied
    /// automatically to this discount. The specification and application of the discounts, to
    /// which a <c>pricing_rule_id</c> is assigned, are completely controlled by the corresponding
    /// pricing rule.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("pricing_rule_id")]
    public string? PricingRuleId { get; init; }

    /// <summary>
    /// The reward IDs corresponding to this discount. The application and
    /// specification of discounts that have <c>reward_ids</c> are completely controlled by the backing
    /// criteria corresponding to the reward tiers of the rewards that are added to the order
    /// through the Loyalty API. To manually unapply discounts that are the result of added rewards,
    /// the rewards must be removed from the order through the Loyalty API.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("reward_ids")]
    public IReadOnlyList<string>? RewardIds { get; init; }

    /// <summary>
    /// Indicates the level at which the discount applies. For <c>ORDER</c> scoped discounts,
    /// Square generates references in <c>applied_discounts</c> on all order line items that do
    /// not have them. For <c>LINE_ITEM</c> scoped discounts, the discount only applies to line items
    /// with a discount reference in their <c>applied_discounts</c> field.
    /// <para>
    /// This field is immutable. To change the scope of a discount, you must delete
    /// the discount and re-add it as a new discount.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("scope")]
    public string? Scope { get; init; }

    /// <summary>
    /// The type of the discount.
    /// <para>
    /// Discounts that do not reference a catalog object ID must have a type of
    /// <c>FIXED_PERCENTAGE</c> or <c>FIXED_AMOUNT</c>.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>
    /// A unique ID that identifies the discount only within this order.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("uid")]
    [MaxLength(60)]
    public string? Uid { get; init; }
}
