using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

/// <summary>
/// Represents additional details of a tender with <c>type</c> <c>CARD</c> or <c>SQUARE_GIFT_CARD</c>
/// </summary>
public record TenderCardDetails
{
    /// <summary>
    /// Represents the payment details of a card to be used for payments. These
    /// details are determined by the payment token generated by Web Payments SDK.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("card")]
    public Card? Card { get; init; }

    /// <summary>
    /// The method used to enter the card's details for the transaction.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("entry_method")]
    public string? EntryMethod { get; init; }

    /// <summary>
    /// The credit card payment's current state (such as <c>AUTHORIZED</c> or
    /// <c>CAPTURED</c>). See <see href="https://developer.squareup.com/reference/square_2021-08-18/objects/TenderCardDetailsStatus">TenderCardDetailsStatus</see>
    /// for possible values.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("status")]
    public string? Status { get; init; }
}
