using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SquareConnectApi.Models;

public record TerminalCheckout
{
    /// <summary>
    /// Represents an amount of money. <c>Money</c> fields can be signed or unsigned.
    /// Fields that do not explicitly define whether they are signed or unsigned are
    /// considered unsigned and can only hold positive amounts. For signed fields, the
    /// sign of the value indicates the purpose of the money transfer. See
    /// <see href="https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts">Working with Monetary Amounts</see>
    /// for more information.
    /// </summary>
    [JsonPropertyName("amount_money")]
    public required Money AmountMoney { get; init; }

    /// <summary>
    /// The ID of the application that created the checkout.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("app_id")]
    public string? AppId { get; init; }

    /// <summary>
    /// Present if the status is <c>CANCELED</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("cancel_reason")]
    public string? CancelReason { get; init; }

    /// <summary>
    /// The time when the <c>TerminalCheckout</c> was created, as an RFC 3339 timestamp.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; init; }

    /// <summary>
    /// An RFC 3339 duration, after which the checkout is automatically canceled.
    /// A <c>TerminalCheckout</c> that is <c>PENDING</c> is automatically <c>CANCELED</c> and has a cancellation reason
    /// of <c>TIMED_OUT</c>.
    /// <para>
    /// Default: 5 minutes from creation
    /// </para>
    /// <para>
    /// Maximum: 5 minutes
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("deadline_duration")]
    public string? DeadlineDuration { get; init; }

    [JsonPropertyName("device_options")]
    public required DeviceCheckoutOptions DeviceOptions { get; init; }

    /// <summary>
    /// A unique ID for this <c>TerminalCheckout</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("id")]
    [StringLength(255, MinimumLength = 10)]
    public string? Id { get; init; }

    /// <summary>
    /// The location of the device where the <c>TerminalCheckout</c> was directed.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("location_id")]
    public string? LocationId { get; init; }

    /// <summary>
    /// An optional note to associate with the checkout, as well as with any payments used to complete the checkout.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("note")]
    [MaxLength(250)]
    public string? Note { get; init; }

    /// <summary>
    /// A list of IDs for payments created by this <c>TerminalCheckout</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("payment_ids")]
    public IReadOnlyList<string>? PaymentIds { get; init; }

    /// <summary>
    /// The type of payment the terminal should attempt to capture from. Defaults to <c>CARD_PRESENT</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("payment_type")]
    public string? PaymentType { get; init; }

    /// <summary>
    /// An optional user-defined reference ID that can be used to associate
    /// this <c>TerminalCheckout</c> to another entity in an external system. For example, an order
    /// ID generated by a third-party shopping cart. The ID is also associated with any payments
    /// used to complete the checkout.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("reference_id")]
    [MaxLength(40)]
    public string? ReferenceId { get; init; }

    /// <summary>
    /// The status of the <c>TerminalCheckout</c>.
    /// Options: <c>PENDING</c>, <c>IN_PROGRESS</c>, <c>CANCEL_REQUESTED</c>, <c>CANCELED</c>, <c>COMPLETED</c>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("status")]
    public string? Status { get; init; }

    /// <summary>
    /// The time when the <c>TerminalCheckout</c> was last updated, as an RFC 3339 timestamp.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("updated_at")]
    public string? UpdatedAt { get; init; }
}
